# Generated by Django 4.2.3 on 2023-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_message', models.TextField(default='Стартовое сообщение')),
                ('get_photo_btn_text', models.TextField(default='Получить фото')),
                ('image', models.TextField(default='картинка photo:123')),
            ],
        ),
    ]
