# Generated by Django 4.2.3 on 2023-08-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
