# Generated by Django 4.2.3 on 2023-07-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_bought_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_message', models.TextField(default='Стартовое сообщение')),
                ('payment_link_message', models.TextField(default='Вот вам ссылка на <a href="{}">оплату</a> ')),
                ('success_payment_message', models.TextField(default='Вы оплатили, пользуйтесь ')),
                ('three_days_left_payment_message', models.TextField(default='У вас осталось 3 дня, продлите доступ ')),
                ('no_access_message', models.TextField(default='У вас больше нет доступа, пополните пожалуйста ')),
            ],
        ),
    ]
