# Generated by Django 4.2 on 2023-05-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='channel_link',
            field=models.CharField(default='https://t.me/test_gpt', max_length=100),
        ),
    ]
