# Generated by Django 4.2 on 2023-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_settings_channel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='back_button',
            field=models.CharField(default='Назад', max_length=100),
        ),
    ]
