# Generated by Django 4.2 on 2023-05-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_settings_back_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='gpt_process_started',
            field=models.TextField(default='Сейчас ответим'),
        ),
    ]
