# Generated by Django 4.2 on 2023-05-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_settings_gpt_process_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='max_gpt_context_limit',
            field=models.TextField(default='Достигнуто ограничение по числу сообщений в диалоге, попробуйте задать вопрос в новом диалоге'),
        ),
    ]
