# Generated by Django 4.2.3 on 2023-07-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_settings_access_extended_settings_invite_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='num_of_months',
            new_name='subscribe_type',
        ),
    ]
