# Generated by Django 4.2 on 2023-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_settings_max_gpt_context_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='proile',
            name='generate_image_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='generate_image_command',
            field=models.CharField(default='Сгенерировать изображение', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='generate_image_prompt',
            field=models.TextField(default='Напишите описание для генерации изображения', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='stop_generate_button',
            field=models.CharField(default='Отменить генерацию', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='stop_generate_message',
            field=models.TextField(default='Вы отменили генерацию'),
        ),
    ]
