# Generated by Django 4.2.3 on 2023-08-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
