# Generated by Django 4.2 on 2023-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_proile_generate_image_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='start_generate_message',
            field=models.TextField(default='Генрация началась'),
        ),
    ]
