# Generated by Django 4.2 on 2023-05-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_settings_start_generate_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое сообщения')),
                ('group', models.CharField(choices=[('ALL', 'всем'), ('ADMINS', 'администратор')], default='ADMINS', max_length=100)),
                ('is_send', models.BooleanField(default=False, verbose_name='Сообщение отправлено')),
                ('target_users', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
