# Generated by Django 4.2.3 on 2023-08-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_tariff_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='file_link',
            field=models.TextField(default=''),
        ),
    ]
