# Generated by Django 4.2 on 2023-05-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='proile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
