# Generated by Django 4.2.3 on 2023-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_settings_about_settings_close_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='start_message',
            field=models.TextField(default='Что сейчас в доступе?'),
        ),
    ]
