# Generated by Django 4.2.3 on 2023-08-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_settings_start_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about_btn_text',
            field=models.TextField(default='Про автора Бьютимаргиналии'),
        ),
        migrations.AddField(
            model_name='settings',
            name='channel_btn_text',
            field=models.TextField(default='Закрытый канал #нахуйлогии'),
        ),
    ]
