# Generated by Django 4.2.3 on 2023-08-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_settings_about_btn_text_settings_channel_btn_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='close_channel_btn_text',
            field=models.TextField(default='С меня достаточно'),
        ),
    ]
