# Generated by Django 4.2.3 on 2023-08-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_settings_about_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='channel_msg',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='settings',
            name='group_msg',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_group',
            field=models.TextField(default='Мы любим людей, которым вечно всего мало. Значит, вы всегда хотите большего. \n\nПоэтому вы можете оплатить тариф «База + чат инсайтов». '),
        ),
    ]
