# Generated by Django 4.2.3 on 2023-08-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_settings_channel_msg_settings_group_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='channel_msg',
            field=models.TextField(default='Дает доступ к закрытому каналу на 1 месяц (я напомню вам обновить подписку, не переживайте).'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='group_msg',
            field=models.TextField(default='Мы любим людей, которым вечно всего мало. Значит, вы всегда хотите большего. \n\nПоэтому вы можете оплатить тариф «База + чат инсайтов». '),
        ),
    ]
