# Generated by Django 4.2.3 on 2023-08-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_settings_channel_msg_alter_settings_group_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='buy_group_btn',
            field=models.TextField(default='Тариф «База + чат инсайтов» 2 490 Р'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='group_msg',
            field=models.TextField(default='Дает доступ к закрытому каналу на 1 месяц (я напомню вам обновить подписку, не переживайте) + доступ к закрытому чату с другими участниками, куда вы можете писать свои инсайты и читать чужие, перечитывать и держать перед глазами, чтобы не упускать философию #нахуйлогии из своей жизни. И делать запросы на интересующие вас темы. '),
        ),
    ]
