# Generated by Django 4.2.3 on 2023-08-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_settings_buy_group_btn_alter_settings_group_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_ending_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
