# Generated by Django 4.2.3 on 2023-09-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_profile_premium_ending_alerted'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='buy_check_list_btn_text',
            field=models.TextField(default='Купить чеклист'),
        ),
        migrations.AddField(
            model_name='settings',
            name='buy_check_list_text',
            field=models.TextField(default='Благодарим вас за приобретение продукта!\n\nВы присоединились к элитному кругу покупателей, входящих в топ-100, и поэтому мы рады предоставить вам специальный бонус:\n\nhttps://drive.google.com/file/d/1QJ8SybH1hjSG_CbsRhge-rskpZksWbDY/view?usp=share_link \ndocument:BQACAgIAAxkBAAIZVWT4Dy2IK2SpD8lXkJgYZEYclYu1AAKSMAAC14nBS8qzs1edYdhBMAQ'),
        ),
        migrations.AddField(
            model_name='settings',
            name='check_list_btn_text',
            field=models.TextField(default='Чеклист «Дорогое лицо»'),
        ),
        migrations.AddField(
            model_name='settings',
            name='check_list_text',
            field=models.TextField(default='Все хотят иметь кожу лучше, чем у них есть: без пор, матовую, сияющую здоровым блеском, подтянутую, плотную, гладкую и однотонную. И желательно – сохранить результат надолго. \n\nКажется, что методов куча и постоянно появляются новые – как проверить каждый, ведь их много, а опыт подруг не показателен, ведь их кожа другая и они другого возраста?!\n\nА что, если я скажу, что МНОГО аппаратов и препаратов, а методов, по которому они работают – НЕМНОГО? И добавлю, что возраст и тип кожи вообще не решающие факторы в выборе метода? Так и есть. \n\nВместе с косметологами пространства Lume21 Маша разработала самый понятный путь к идеальной коже для всех, независимо от возраста, пола и типа кожи, города и даже страны, где вы находитесь. \n\nЭтот чеклист будет работать на вас всегда и везде – даже когда косметологов заменят роботы. Он будет передаваться из поколения в поколение. И ваши дети и внуки скажут вам за него спасибо. \n\nОн не просто покажет, какие есть методы и продукты, но и научит вас правильно их выбирать – отсеивая все ненужное и не тратя время и деньги впустую. Он научит вас так хорошо, что косметологи будут бояться впаривать вам ненужное.\n\nСтоимость 3 300 Р'),
        ),
    ]
