# Generated by Django 4.2.3 on 2023-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_settings_buy_check_list_btn_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
