# Generated by Django 4.2.3 on 2023-09-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_end_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
