# Generated by Django 4.2.3 on 2023-10-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_profile_premium_end_alerted'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='buy_group_year_btn',
            field=models.TextField(default='Доступ на год со скидкой 20% 14\xa0290Р'),
        ),
        migrations.AddField(
            model_name='settings',
            name='group_year_msg',
            field=models.TextField(default='Для истинных адептов #нахуйлогии – доступ к закрытому каналу на 1 год по супервыгодной цене. \n\nНажимая на кнопку "Оплатить" и отправляя данные формы, Вы принимаете условия публичной оферты (https://disk.yandex.ru/i/8BR_7WMy2CJZSw) и соглашаетесь с политикой конфиденциальности. (https://disk.yandex.ru/i/Yiafa2cOOqJUCg)'),
        ),
    ]
