# Generated by Django 3.2.11 on 2023-10-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_settings_buy_group_year_btn_settings_group_year_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_subscribe_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='form_state',
            field=models.CharField(blank=True, choices=[('PI', 'ввод номера')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
