# Generated by Django 4.2.3 on 2023-12-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_settings_enter_your_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='binding_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
